prereqCharts:
  - postgresql:
      repo: stable

additionalValues:
  - repo: https://github.com/travelaudience/armador.git
    path:
      - docs/example/overrideValues.yaml

cluster:
  minikube:
    contextName: minikube
